common:
  env: 'develop'
  port: 3000
planet:
  size: 10
  obstaclesNumber: 10
  behaviorMove:
    - cardinal: 'N'
      axis: 'y'
      command: 
        - type: 'F'
          direction: 0
        - type: 'B'
          direction: 1
        - type: 'R'
          cardinal: 'E'
        - type: 'L'
          cardinal: 'W'
    - cardinal: 'E'
      axis: 'x'
      command: 
        - type: 'F'
          direction: 0
        - type: 'B'
          direction: 1
        - type: 'R'
          cardinal: 'S'
        - type: 'L'
          cardinal: 'N'
    - cardinal: 'S'
      axis: 'y'
      command: 
        - type: 'F'
          direction: 1
        - type: 'B'
          direction: 0
        - type: 'R'
          cardinal: 'W'
        - type: 'L'
          cardinal: 'E'  
    - cardinal: 'W'
      axis: 'x'
      command: 
        - type: 'F'
          direction: 1
        - type: 'B'
          direction: 0
        - type: 'R'
          cardinal: 'N'
        - type: 'L'
          cardinal: 'S'